version: '3'
services:
  mongodb:
    image: mongo
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
    - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=mongodb
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
     - /home/kakrol/mosquitto/config:/mosquitto/config
     - /home/kakrol/mosquitto/data:/mosquitto/data
     - /home/kakrol/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
  # first_task:
  #   container_name: clients
  #   image: first_task
  #   restart: always
  #   network_mode: "host"
volumes:
  mongo-data:
    driver: local